getAll & getById + jwt
elemetorkamatech2/storage-actions pull request #24
Opened 2023-06-20 21:16 UTC by chanaKastner

2023-06-21 10:33 UTC, elishevapro approved these changes

2023-06-21 10:33 UTC, elishevapro commented on api/models/permission-check.js
> +
שורה מיותרת
וכן,חסרה שורה בסוף המסמך

2023-06-21 10:33 UTC, elishevapro commented on api/controller/websiteController.js
> +};
חסרה שורה בסוף המסמך

2023-06-21 10:33 UTC, elishevapro commented on api/middleware/auth.js
> +};
חסרה שורה בסוף המסמך

2023-06-21 10:33 UTC, elishevapro commented on api/routes/websiteRoute.js
>  module.exports = router;
חסרה שורה בסוף המסמך

2023-06-21 10:33 UTC, elishevapro commented on api/services/website.service.js
> +};
חסרה שורה בסוף המסמך

2023-06-21 10:33 UTC, elishevapro commented on api/validate.js
> +  'type-domain',
לא צריך לשנות ל domain type   אם הכוונה לסוג דומיין, אם כן, שימי לב לזה בכל הפרוייקט

2023-06-21 10:33 UTC, elishevapro commented on api/validate.js
>  const dns = require('dns');
require 
צריך להיות בתחילת המסמך

וכן, תורידי את ההערות 
        resolve(true); // domain is available
        resolve(false); // domain is not available

ומה זה ההערה הזו 
// Tighten password policy
?

וכן , חסרה שורה בסוף המסמך

2023-06-21 10:33 UTC, elishevapro commented on app.js
> -
למה להוריד שורה בסוף המסמך? היא נדרשת ע"פ הESLINT

2023-06-21 10:33 UTC, elishevapro commented on app.log
>  {"level":"INFO","time":"2023-06-14T10:09:14.685Z","pid":16848,"hostname":"רבקה","msg":"my app is listening on http://localhost:3000"}
במיין כבר אין את הקובץ , אז פעם הבאה שתעלי, כנראה לא יעלה לך הקובץ הזה, וזה מה שאמור לקרות

2023-06-21 10:33 UTC, elishevapro commented on package.json
> +    "validator": "^13.9.0",
זה 3 תלויות שונות?
validator, validatorjs, validators

2023-06-21 10:46 UTC, chanaKastner commented on api/models/permission-check.js
> +
בטעות המסמך הזה עלה 
מחקתי אותו כבר...

2023-06-21 11:56 UTC, elishevapro approved these changes

2023-06-21 11:56 UTC, elishevapro commented on test/test.js
> +
שורה מיותרת

2023-06-25 21:11 UTC, elemetorkamatech2 requested changes

2023-06-25 21:11 UTC, elemetorkamatech2 commented on app.log
>  {"level":"INFO","time":"2023-06-14T10:09:14.685Z","pid":16848,"hostname":"רבקה","msg":"my app is listening on http://localhost:3000"}
אם היא תעלה אותו אז שוב הוא יופיע במיין
היא חייבת להוריד אותו מהקומיט הזה

2023-06-25 21:16 UTC, elishevapro commented on app.log
>  {"level":"INFO","time":"2023-06-14T10:09:14.685Z","pid":16848,"hostname":"רבקה","msg":"my app is listening on http://localhost:3000"}
נכון, למחוק אותו ולהעלות קומיט חדש בPR הזה.

2023-06-25 21:21 UTC, chanakamin commented on api/controller/websiteController.js
> +    websiteModel.findById(websiteId)
async await

2023-06-25 21:23 UTC, chanakamin commented on api/controller/websiteController.js
> +        res.status(412).send({ success: false, message: result.message });
why 412?

2023-06-26 07:31 UTC, chanaKastner commented on api/controller/websiteController.js
> +        res.status(412).send({ success: false, message: result.message });
לא אני כתבתי את הפונקציה,
יש לשאול את הכותב...

2023-06-26 07:34 UTC, chanaKastner commented on app.js
> -
בכל הקבצים השארתי שורה ריקה בסוף לפי כללי הeslint
מוזר שלא רואים את זה בגיט...

2023-06-28 10:14 UTC, elemetorkamatech2 approved these changes

2023-06-28 10:15 UTC, merged